spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: order_route
          uri: lb://mall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: mall_host_route
          uri: lb://mall-product
          predicates:
            - Host=mall.com,item.mall.com

        - id: mall_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com

        - id: mall_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.mall.com

        - id: mall_cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.mall.com

        - id: mall_order_route
          uri: lb://mall-order
          predicates:
            - Host=order.mall.com

        - id: mall_member_route
          uri: lb://mall-member
          predicates:
            - Host=member.mall.com

        - id: mall_seckill_route
          uri: lb://mall-seckill
          predicates:
            - Host=seckill.mall.com



#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

  ## 前端项目，/api
## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree